package com.jihai.bitfree.enums;

public enum ConfigEnum {

    SECRET,
    TOP_POST_ID,
    MAIL_SECRET,
    DEFAULT_PASSWORD,
    DEFAULT_POSTER,
    SENSITIVE_WORDS,
    LIMIT_COUNT_PER_SECOND,
    DEFAULT_AVATAR,
    WEB_STATISTICS,
    ROBOT_URL,
    SKIP_MONITOR_MESSAGE,
    MODIFY_SETTINGS_NOTIFICATION_ID,
    TASK_COMPLETE_USER_LIST,
    MESSAGE_HEARTBEAT_SECRET

    ;


}
