package com.jihai.bitfree.constants;

public interface Constants {
    String TOP_POST_ID = "TOP_POST_ID";
    String SECRET = "SECRET";
    String TOKEN = "token";
    String NOT_LOGIN = "请重新登录!";
    String EMAIL_SECRET = "MAIL_SECRET";
    String DEFAULT_PASSWORD_KEY = "DEFAULT_PASSWORD";
    String DEFAULT_POSTER = "DEFAULT_POSTER";
    String SENSITIVE_WORDS = "SENSITIVE_WORDS";
    String XSS_EXCLUDE_URLS = "XSS_EXCLUDE_URLS";
    String WEB_STATISTICS = "WEB_STATISTICS";
    String ROBOT_URL = "ROBOT_URL";
    String HEARTBEAT_SECRET = "MESSAGE_HEARTBEAT_SECRET";
    Long SYSTEM_DEFAULT_USER_ID = -1L;
    String MODIFY_SETTINGS_NOTIFICATION_ID = "MODIFY_SETTINGS_NOTIFICATION_ID";
    String TASK_COMPLETE_USER_LIST = "TASK_COMPLETE_USER_LIST";
    /**
     * 过滤历史操作记录的时间
     */
    String FILTER_OPERATION_HISTORY_TIME = "2023-12-21 00:00:00";
}
